name: Set Environment
description: "Configures GitHub runner environment with caching, necessary dependencies, and cluster authentication"

inputs:
  cache-venv-key:
    description: "An explicit key for restoring and saving the cache, passed down to cache GitHub action."
    required: true
    default: "set-env"
  poetry-install-args:
    description: "Arguments passed directly to the Poetry installation script. For example --with test."
    required: false

runs:
  using: composite
  steps:
    - name: Set Permissions for Clean Up
      shell: bash
      run: |
        sudo chown -R $USER:$USER ${{ github.workspace }}

    - name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3.8 - --version 1.4.2 -y
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Cache venv
      uses: actions/cache@v3
      id: cache-venv
      with:
        path: .venv/
        key: ${{ runner.os }}-${{ inputs.cache-venv-key }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install Dependencies
      shell: bash
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: |
        poetry config virtualenvs.in-project true
        poetry config http-basic.kfp build ${{github.token}}
        poetry install --no-interaction ${{ inputs.poetry-install-args }} -vvv --sync

    - name: Set SHA Short
      shell: bash
      run: |
        echo "GITHUB_SHA=${{ github.sha }}"
        echo "GITHUB_SHA_SHORT=${GITHUB_SHA::8}" >> $GITHUB_ENV
