name: Check Pull Request

on:
  pull_request:
    branches:
      - "develop"
    paths-ignore:
      - "**.md"
      - "notebooks/"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  upload_artifacts:
    name: Upload Test Data to S3
    runs-on: [ self-hosted, linux, x64, project_name-python38]
    steps:
      - name: Configure AWS Credentials # Setup AWS Credentials so that the Deploy step can sync an s3 location
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::<aws_account_id>:role/<role_name>
          aws-region: eu-west-1
          role-skip-session-tagging: true
          role-duration-seconds: 1200

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Environment
        uses: ./.github/actions/set-environment
        with:
          cache-venv-key: project_name
          poetry-install-args: --with test

      - name: Upload Test Data to S3
        shell: bash
        run: |
          if [ -d .git ]; then rm -Rf .git; fi
          source .venv/bin/activate
          python helpers/upload_test_data_to_s3.py

  run-tests:
    name: Run Tests
    runs-on: [ self-hosted, linux, x64, project_name-python38]
    needs: [ upload_artifacts ]
    steps:
      - name: Configure AWS Credentials # Setup AWS Credentials so that the Deploy step can sync an s3 location
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::<aws_account_id>:role/<role_name>
          aws-region: eu-west-1
          role-skip-session-tagging: true
          role-duration-seconds: 1200

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Environment
        uses: ./.github/actions/set-environment
        with:
          cache-venv-key: project_name
          poetry-install-args: --with test

      - name: Execute Unit Tests
        shell: bash
        run: |
          if [ -d .git ]; then rm -Rf .git; fi
          source .venv/bin/activate
          pytest tests/unit_tests/ -v

      - name: Execute Integration Tests
        shell: bash
        run: |
          if [ -d .git ]; then rm -Rf .git; fi
          source .venv/bin/activate
          pytest tests/integration_tests/ -v
